### ISSUE TITLE
Quickstart for users (quick method) - superadmin account creation is not working on server installation

### ISSUE THREAD

**Issue by gunkaragoz** [bluewave-labs/bluewave-uptime#1019] opened 2024-10-22 18:11 UTC
**Describe the bug**
I have installed uptime on Ubuntu server following the [Quickstart for users (quick method)](https://bluewavelabs.gitbook.io/uptime-manager/users-guide/quickstart#user-quickstart) steps, I can see the UI is up but I can't pass register/login step. I didn't try on my local, probably it would work with localhost.

**To Reproduce**
1. Download Docker compose file
`wget https://raw.githubusercontent.com/bluewave-labs/bluewave-uptime/refs/heads/develop/Docker/dist/docker-compose.yaml`
3. Run `docker compose up` to start the application
4. Now the application is running at `http://<SERVER-IP>`
5. Open application via server IP 
6. Signup > Go to `http://<SERVER-IP>/register` and fill necessary fields (name,surname,email,password). It goes back to signup screen.
7. Login > Go to `http://<SERVER-IP>/login` use credentials that are created
8. `Network error` occurs since Request URL is wrong. Console shows errors with `localhost` instead of IP. 
Also it's not a good idea to pass password in plain text.

**Expected behavior**
Following the steps simply should work and it should allow me to login with the credentials I created. 

**Screenshots**
![image](https://github.com/user-attachments/assets/243aab18-2f3a-4535-a7ae-11ebf9e74e0c)

![image](https://github.com/user-attachments/assets/c6c6bad3-4796-4921-86c7-648a6a5219ce)

 - Browser Chrome 130.0.6723.58 
 - Server Ubuntu 22.04 on DO

**Comment by jennifer-gan** [comment] 2024-10-22 20:20
It looks working on my end with ipaddress
![Screenshot from 2024-10-22 16-19-39](https://github.com/user-attachments/assets/66eb1017-f842-4fb6-9269-20af9af6da11)

**Comment by jennifer-gan** [comment] 2024-10-22 20:25
looks working on my end
![Screenshot from 2024-10-22 16-25-18](https://github.com/user-attachments/assets/854bf0e0-da3b-47b9-833a-7c0fc766ea11)
![Screenshot from 2024-10-22 16-24-18](https://github.com/user-attachments/assets/c2426c3a-c2bd-401c-839b-d409b2ab1791)

**Comment by gorkem-bwl** [comment] 2024-10-22 20:32
@gunkaragoz For 7, does the network error occur since you entered the wrong IP?

**Comment by gunkaragoz** [comment] 2024-10-22 20:49
> @gunkaragoz For 7, does the network error occur since you entered the wrong IP?

No, I just spun up a new droplet, followed the given steps and installed uptime. I only have one public IP.

**Comment by gorkem-bwl** [comment] 2024-10-22 21:22
Let me check this on a new droplet.

**Comment by gorkem-bwl** [comment] 2024-10-22 22:49
@ajhollid I can reproduce this by going over the steps one by one mentioned by @gunkaragoz. I created a DO and sent over the details to you.

**Comment by gorkem-bwl** [comment] 2024-10-23 01:24
@gunkaragoz, I discussed this with Alex, and it turns out the document was intended for local installation, which wasn't made clear, leading to confusion. The server installation document will be available shortly.

**Comment by jennifer-gan** [comment] 2024-10-23 17:06
@gunkaragoz, I used the images as in your step 1, and running locally , all are working, if that was the intention

**Comment by ajhollid** [comment] 2024-10-31 06:44
This has been resolved with a new docker compose configuration

**Closed by ajhollid** 2024-10-31 06:44 UTC
